name: Debugging Puppeteer Script

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '6,26,46 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install Dependencies
      run: |
        echo "Installing Puppeteer and required tools..."
        sudo apt-get update
        sudo apt-get install -y xvfb libnss3 libxss1 libasound2 libatk1.0-0 libgtk-3-0
        npm install puppeteer-extra puppeteer-extra-plugin-stealth proxy-chain --force
        npm install cloudflare-scraper

    # - name: Debug Chromium Path
    #   run: |
    #     echo "Checking Chromium executable path..."
    #     ls -la /usr/bin | grep chromium
    #     ls -la /snap/bin | grep chromium

    - name: Create fetch-site.mjs
      run: |
        echo "Creating fetch-site.mjs..."
        pwd
        ls -la
        cat << 'EOF' > fetch-site.mjs
        import got from 'got';
        import fs from 'fs';
        import path from 'path';

        (async () => {
          const baseURL = 'https://www.act.org.nz/';
          const directory = 'act.org.nz_site_tracking';

          // Ensure the directory exists
          if (!fs.existsSync(directory)) {
            fs.mkdirSync(directory, { recursive: true });
            console.log(`Directory created: ${directory}`);
          }

          try {
            console.log(`Fetching ${baseURL} using Cloudflare Scraper with increased timeout...`);

            // Fetch the main page with increased timeout
            const options = {
              timeout: {
                send: 3500
              },
            };

            const response = await got(baseURL, options);

            // Log the first 500 characters of the response body for debugging
            console.log('Response Body Preview:', response);

          } catch (err) {
            // Catch and log any error during the main request
            console.error('Error during Cloudflare Scraper operation:', err);
          }
        })();


        EOF
        echo "fetch-site.mjs created successfully."

    - name: Verify fetch-site.mjs
      run: |
        echo "Verifying fetch-site.mjs exists..."
        ls -la
        cat fetch-site.mjs || echo "Error: fetch-site.mjs does not exist!"

    - name: Debug Environment
      run: |
        echo "Current working directory:"
        pwd
        echo "Node.js version:"
        node -v
        echo "Installed npm packages:"
        npm list --depth=0

    # - name: Run Puppeteer in Headful Mode
    #   run: |
    #     echo "Starting Xvfb..."
    #     Xvfb :99 -ac & # Start Xvfb on display :99
    #     export DISPLAY=:99 # Set the display environment variable
    #     echo "Running Puppeteer script..."
    #     node fetch-site.mjs

    - name: Run Puppeteer with Stealth
      run: |
        echo "Starting Xvfb..."
        Xvfb :99 -ac &
        export DISPLAY=:99
        echo "Running Puppeteer script..."
        node fetch-site.mjs

    - name: Verify Output Files
      run: |
        echo "Checking act.org.nz_site_tracking directory..."
        ls -la act.org.nz_site_tracking || echo "Error: Output directory is missing!"
        echo "Verifying index.html..."
        if [ -f act.org.nz_site_tracking/index.html ]; then
          echo "index.html exists."
        else
          echo "Error: index.html is missing!"
        fi

    - name: Commit and Push Changes
      run: |
        echo "Configuring Git..."
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        echo "Staging files..."
        git add -A
        echo "Files staged for commit:"
        git diff --cached --name-only || echo "Error: No files staged."
        timestamp=$(date -u)
        echo "Attempting to commit..."
        git commit -m "Latest website snapshot: ${timestamp}" || echo "No changes to commit."
        echo "Attempting to push changes..."
        git push || echo "Error: Failed to push changes."
