name: Debugging Puppeteer Script

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '6,26,46 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install Dependencies
      run: |
        echo "Installing Puppeteer and required tools..."
        sudo apt-get update
        sudo apt-get install -y xvfb libnss3 libxss1 libasound2 libatk1.0-0 libgtk-3-0
        npm install puppeteer-extra puppeteer-extra-plugin-stealth proxy-chain --force

    # - name: Debug Chromium Path
    #   run: |
    #     echo "Checking Chromium executable path..."
    #     ls -la /usr/bin | grep chromium
    #     ls -la /snap/bin | grep chromium

    - name: Create fetch-site.mjs
      run: |
        echo "Creating fetch-site.mjs..."
        pwd
        ls -la
        cat << 'EOF' > fetch-site.mjs
        import puppeteer from 'puppeteer-extra';
        import StealthPlugin from 'puppeteer-extra-plugin-stealth';
        import fs from 'fs';

        // Apply the stealth plugin
        puppeteer.use(StealthPlugin());

        (async () => {
          const baseURL = 'https://www.act.org.nz/';

          console.log('Launching Puppeteer with Stealth Plugin...');

          const browser = await puppeteer.launch({
            executablePath: '/usr/bin/chromium-browser', // Path to system-installed Chromium
            headless: false, // Run in headful mode
            args: ['--no-sandbox', '--disable-setuid-sandbox'],
          });
          const page = await browser.newPage();

          try {
            console.log(`Navigating to ${baseURL}...`);
            await page.goto(baseURL, { waitUntil: 'networkidle2', timeout: 60000 });

            console.log('Page loaded. Saving Cloudflare response...');

            // Save the entire page content to a local file
            const content = await page.content();
            fs.writeFileSync('cloudflare_response.html', content);
            console.log('Cloudflare response saved to cloudflare_response.html');

            // Optionally, log the page title and headers
            const title = await page.title();
            console.log(`Page title: ${title}`);

            const headers = await page.evaluate(() => JSON.stringify(window.performance.getEntriesByType('navigation')[0], null, 2));
            console.log('Page headers:');
            console.log(headers);
          } catch (err) {
            console.error('Error during Puppeteer operation:', err);
          } finally {
            console.log('Closing Puppeteer...');
            await browser.close();
            console.log('Puppeteer closed.');
          }

        })();


        EOF
        echo "fetch-site.mjs created successfully."

    - name: Verify fetch-site.mjs
      run: |
        echo "Verifying fetch-site.mjs exists..."
        ls -la
        cat fetch-site.mjs || echo "Error: fetch-site.mjs does not exist!"

    - name: Debug Environment
      run: |
        echo "Current working directory:"
        pwd
        echo "Node.js version:"
        node -v
        echo "Installed npm packages:"
        npm list --depth=0

    # - name: Run Puppeteer in Headful Mode
    #   run: |
    #     echo "Starting Xvfb..."
    #     Xvfb :99 -ac & # Start Xvfb on display :99
    #     export DISPLAY=:99 # Set the display environment variable
    #     echo "Running Puppeteer script..."
    #     node fetch-site.mjs

    - name: Run Puppeteer with Stealth
      run: |
        echo "Starting Xvfb..."
        Xvfb :99 -ac &
        export DISPLAY=:99
        echo "Running Puppeteer script..."
        node fetch-site.mjs

    - name: Verify Output Files
      run: |
        echo "Checking act.org.nz_site_tracking directory..."
        ls -la act.org.nz_site_tracking || echo "Error: Output directory is missing!"
        echo "Verifying index.html..."
        if [ -f act.org.nz_site_tracking/index.html ]; then
          echo "index.html exists."
        else
          echo "Error: index.html is missing!"
        fi

    - name: Commit and Push Changes
      run: |
        echo "Configuring Git..."
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        echo "Staging files..."
        git add -A
        echo "Files staged for commit:"
        git diff --cached --name-only || echo "Error: No files staged."
        timestamp=$(date -u)
        echo "Attempting to commit..."
        git commit -m "Latest website snapshot: ${timestamp}" || echo "No changes to commit."
        echo "Attempting to push changes..."
        git push || echo "Error: Failed to push changes."
