name: Track Entire Website Changes with wget

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '6,26,46 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v4

    - name: Fetch entire website with wget
      run: |
        mkdir -p website_backup
        wget --recursive --no-clobber --page-requisites --html-extension --convert-links --execute robots=off \
          --accept js,html,css,png,jpg --directory-prefix=website_backup \
          --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36" \
          --tries=3 --wait=5 \
          --verbose https://www.act.org.nz/ || echo "wget failed with exit code $?"
    - name: Commit and push changes
      run: |
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        
        # Count the number of files changed
        file_count=$(git diff --cached --name-only | wc -l)
        
        # List the files changed
        files_changed=$(git diff --cached --name-only | tr '\n' ', ')
        
        # Commit with the list of files changed
        git commit -m "Latest website snapshot: ${timestamp} | Files changed: ${file_count} | Files: ${files_changed}" || exit 0
        
        git push
