name: Debugging Website Tracking with Puppeteer

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '6,26,46 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install Puppeteer
      run: |
        echo "Installing Puppeteer..."
        npm install puppeteer@latest

    - name: Debug Environment and File System
      run: |
        echo "Current directory:"
        pwd
        echo "Contents of current directory before running Puppeteer:"
        ls -la
        echo "Node.js version:"
        node -v
        echo "Installed npm packages:"
        npm list --depth=0

    - name: Run Puppeteer with Debugging
      run: |
        echo "Running Puppeteer script..."
        mkdir -p act.org.nz_site_tracking
        node fetch-site.mjs || echo "Puppeteer script failed."
        echo "Contents of act.org.nz_site_tracking after Puppeteer script:"
        ls -la act.org.nz_site_tracking

    - name: Verify Files Before Commit
      run: |
        echo "Verifying files exist before staging:"
        ls -la act.org.nz_site_tracking
        echo "Checking specific files:"
        if [ -f "act.org.nz_site_tracking/index.html" ]; then
          echo "index.html exists"
        else
          echo "index.html is missing!"
        fi

    - name: Commit and Push Changes with Debugging
      run: |
        echo "Configuring Git user..."
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"

        echo "Staging files for commit..."
        git add -A
        echo "Files staged:"
        git diff --cached --name-only || echo "No files staged."

        timestamp=$(date -u)
        
        # Commit files
        echo "Attempting to commit files..."
        git commit -m "Latest website snapshot: ${timestamp}" || echo "No changes to commit."
        
        # Push changes
        echo "Attempting to push changes..."
        git push || echo "Push failed."

    - name: Final Verification
      run: |
        echo "Final check of repository directory:"
        ls -la
